language: php

sudo: false

php:
  - 7.1
  - 7.2

env:
  global:
    - DEFAULT=1
    - APPLICATION_ENV=devtest
    - APPLICATION_STORE=DE

matrix:
  include:
    - php: 7.2
      env: CHECKS=1 DEFAULT=0

  fast_finish: true

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/console t:g ; fi
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept build ; fi
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run ; fi
  - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi

notifications:
  email: false
